// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1utjjo7x95hUFOpfbcLztxgsjeWJ9QgM',
    appId: '1:524398845135:android:31e98d215d53d9ec752bba',
    messagingSenderId: '524398845135',
    projectId: 'ecommerceapp-5c7a2',
    storageBucket: 'ecommerceapp-5c7a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjoIC5Sfp7DASwPyfaLsd664aqMz2NWo',
    appId: '1:524398845135:ios:5c559b3681557533752bba',
    messagingSenderId: '524398845135',
    projectId: 'ecommerceapp-5c7a2',
    storageBucket: 'ecommerceapp-5c7a2.appspot.com',
    androidClientId: '524398845135-ekinhjq8kp2f7rdmum13mj38pl7skr8c.apps.googleusercontent.com',
    iosClientId: '524398845135-rv87pp1u80ii0qcevnhacgjhoevnfhkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.occasionease',
  );

}